version: '3.8'
services:
  gateway:
    build: shareit-gateway
    image: dock_gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
    - server
    environment:
      - TZ=Moscow/Europe
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: shareit-server
    image: dock_server
    container_name: shareit_server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USER=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin